// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/blogs/:blogHandle/:articleHandle": {
    params: {
      "blogHandle": string;
      "articleHandle": string;
    };
  };
  "/api/:version/graphql.json": {
    params: {
      "version": string;
    };
  };
  "/sitemap/:type/:page.xml": {
    params: {
      "type": string;
      "page": string;
    };
  };
  "/blogs/:blogHandle": {
    params: {
      "blogHandle": string;
    };
  };
  "/collections/:handle": {
    params: {
      "handle": string;
    };
  };
  "/account/authorize": {
    params: {};
  };
  "/collections": {
    params: {};
  };
  "/policies/:handle": {
    params: {
      "handle": string;
    };
  };
  "/products/:handle": {
    params: {
      "handle": string;
    };
  };
  "/account/logout": {
    params: {};
  };
  "/collections/all": {
    params: {};
  };
  "/policies": {
    params: {};
  };
  "/account/login": {
    params: {};
  };
  "/discount/:code": {
    params: {
      "code": string;
    };
  };
  "/sustainability": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/pages/:handle": {
    params: {
      "handle": string;
    };
  };
  "/robots.txt": {
    params: {};
  };
  "/best-sellers": {
    params: {};
  };
  "/blogs": {
    params: {};
  };
  "/gift-cards": {
    params: {};
  };
  "/size-guide": {
    params: {};
  };
  "/countdown": {
    params: {};
  };
  "/shipping": {
    params: {};
  };
  "/account": {
    params: {};
  };
  "/account/orders": {
    params: {};
  };
  "/account/orders/:id": {
    params: {
      "id": string;
    };
  };
  "/account/addresses": {
    params: {};
  };
  "/account/profile": {
    params: {};
  };
  "/account/*": {
    params: {
      "*": string;
    };
  };
  "/careers": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/returns": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/cart": {
    params: {};
  };
  "/cart/:lines": {
    params: {
      "lines": string;
    };
  };
  "/shop": {
    params: {};
  };
  "/faq": {
    params: {};
  };
  "/new": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/blogs/:blogHandle/:articleHandle" | "/api/:version/graphql.json" | "/sitemap/:type/:page.xml" | "/blogs/:blogHandle" | "/collections/:handle" | "/account/authorize" | "/collections" | "/policies/:handle" | "/products/:handle" | "/account/logout" | "/collections/all" | "/policies" | "/account/login" | "/discount/:code" | "/sustainability" | "/sitemap.xml" | "/pages/:handle" | "/robots.txt" | "/best-sellers" | "/blogs" | "/gift-cards" | "/size-guide" | "/countdown" | "/shipping" | "/account" | "/account/orders" | "/account/orders/:id" | "/account/addresses" | "/account/profile" | "/account/*" | "/careers" | "/contact" | "/privacy" | "/returns" | "/search" | "/about" | "/terms" | "/cart" | "/cart/:lines" | "/shop" | "/faq" | "/new" | "/*";
  };
  "routes/blogs.$blogHandle.$articleHandle.tsx": {
    id: "routes/blogs.$blogHandle.$articleHandle";
    page: "/blogs/:blogHandle/:articleHandle";
  };
  "routes/api.$version.[graphql.json].tsx": {
    id: "routes/api.$version.[graphql.json]";
    page: "/api/:version/graphql.json";
  };
  "routes/sitemap.$type.$page[.xml].tsx": {
    id: "routes/sitemap.$type.$page[.xml]";
    page: "/sitemap/:type/:page.xml";
  };
  "routes/blogs.$blogHandle._index.tsx": {
    id: "routes/blogs.$blogHandle._index";
    page: "/blogs/:blogHandle";
  };
  "routes/collections.$handle.tsx": {
    id: "routes/collections.$handle";
    page: "/collections/:handle";
  };
  "routes/account_.authorize.tsx": {
    id: "routes/account_.authorize";
    page: "/account/authorize";
  };
  "routes/collections._index.tsx": {
    id: "routes/collections._index";
    page: "/collections";
  };
  "routes/policies.$handle.tsx": {
    id: "routes/policies.$handle";
    page: "/policies/:handle";
  };
  "routes/products.$handle.tsx": {
    id: "routes/products.$handle";
    page: "/products/:handle";
  };
  "routes/account_.logout.tsx": {
    id: "routes/account_.logout";
    page: "/account/logout";
  };
  "routes/collections.all.tsx": {
    id: "routes/collections.all";
    page: "/collections/all";
  };
  "routes/policies._index.tsx": {
    id: "routes/policies._index";
    page: "/policies";
  };
  "routes/account_.login.tsx": {
    id: "routes/account_.login";
    page: "/account/login";
  };
  "routes/discount.$code.tsx": {
    id: "routes/discount.$code";
    page: "/discount/:code";
  };
  "routes/sustainability.tsx": {
    id: "routes/sustainability";
    page: "/sustainability";
  };
  "routes/[sitemap.xml].tsx": {
    id: "routes/[sitemap.xml]";
    page: "/sitemap.xml";
  };
  "routes/pages.$handle.tsx": {
    id: "routes/pages.$handle";
    page: "/pages/:handle";
  };
  "routes/[robots.txt].tsx": {
    id: "routes/[robots.txt]";
    page: "/robots.txt";
  };
  "routes/best-sellers.tsx": {
    id: "routes/best-sellers";
    page: "/best-sellers";
  };
  "routes/blogs._index.tsx": {
    id: "routes/blogs._index";
    page: "/blogs";
  };
  "routes/gift-cards.tsx": {
    id: "routes/gift-cards";
    page: "/gift-cards";
  };
  "routes/size-guide.tsx": {
    id: "routes/size-guide";
    page: "/size-guide";
  };
  "routes/countdown.tsx": {
    id: "routes/countdown";
    page: "/countdown";
  };
  "routes/shipping.tsx": {
    id: "routes/shipping";
    page: "/shipping";
  };
  "routes/account.tsx": {
    id: "routes/account";
    page: "/account" | "/account/orders" | "/account/orders/:id" | "/account/addresses" | "/account/profile" | "/account/*";
  };
  "routes/account.orders._index.tsx": {
    id: "routes/account.orders._index";
    page: "/account/orders";
  };
  "routes/account.orders.$id.tsx": {
    id: "routes/account.orders.$id";
    page: "/account/orders/:id";
  };
  "routes/account.addresses.tsx": {
    id: "routes/account.addresses";
    page: "/account/addresses";
  };
  "routes/account.profile.tsx": {
    id: "routes/account.profile";
    page: "/account/profile";
  };
  "routes/account._index.tsx": {
    id: "routes/account._index";
    page: "/account";
  };
  "routes/account.$.tsx": {
    id: "routes/account.$";
    page: "/account/*";
  };
  "routes/careers.tsx": {
    id: "routes/careers";
    page: "/careers";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/privacy.tsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
  "routes/returns.tsx": {
    id: "routes/returns";
    page: "/returns";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/search.tsx": {
    id: "routes/search";
    page: "/search";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/terms.tsx": {
    id: "routes/terms";
    page: "/terms";
  };
  "routes/cart.tsx": {
    id: "routes/cart";
    page: "/cart" | "/cart/:lines";
  };
  "routes/cart.$lines.tsx": {
    id: "routes/cart.$lines";
    page: "/cart/:lines";
  };
  "routes/shop.tsx": {
    id: "routes/shop";
    page: "/shop";
  };
  "routes/faq.tsx": {
    id: "routes/faq";
    page: "/faq";
  };
  "routes/new.tsx": {
    id: "routes/new";
    page: "/new";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};